// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_1nOWWqnatkeLsp1X_1prT6nhhpZbWmM',
    appId: '1:558209200706:web:67ade98f1d404562a473db',
    messagingSenderId: '558209200706',
    projectId: 'hospital-a5d2b',
    authDomain: 'hospital-a5d2b.firebaseapp.com',
    storageBucket: 'hospital-a5d2b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_1nOWWqnatkeLsp1X_1prT6nhhpZbWmM',
    appId: '1:558209200706:android:67ade98f1d404562a473db',
    messagingSenderId: '558209200706',
    projectId: 'hospital-a5d2b',
    storageBucket: 'hospital-a5d2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_1nOWWqnatkeLsp1X_1prT6nhhpZbWmM',
    appId: '1:558209200706:ios:67ade98f1d404562a473db',
    messagingSenderId: '558209200706',
    projectId: 'hospital-a5d2b',
    storageBucket: 'hospital-a5d2b.firebasestorage.app',
    iosBundleId: 'com.graphicera.hospital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_1nOWWqnatkeLsp1X_1prT6nhhpZbWmM',
    appId: '1:558209200706:ios:67ade98f1d404562a473db',
    messagingSenderId: '558209200706',
    projectId: 'hospital-a5d2b',
    storageBucket: 'hospital-a5d2b.firebasestorage.app',
    iosBundleId: 'com.graphicera.hospital',
  );
}
